name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  check:
    strategy:
      matrix:
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
      fail-fast: false
    runs-on: ${{ matrix.image }}
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@3215144ef6367f915ece1867ff66e63ad92bd9f4 # v1.62.1

      - name: Check
        run: nix flake check

  action:
    strategy:
      matrix:
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
      fail-fast: false
    runs-on: ${{ matrix.image }}
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@3215144ef6367f915ece1867ff66e63ad92bd9f4 # v1.62.1
        with:
          shell: codex

      - name: Run rsync
        uses: ./. # zizmor: ignore[unpinned-uses]
        with:
          server: trev.zip
          module: codex
          remote-path: auth.json
          local-path: ~/.codex/auth.json
          secret: ${{ secrets.RSYNC_SECRET }}

      - name: Run codex
        run: codex exec -m gpt-5.3-codex-spark "hello"
