name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@2fc360eefced0d01fc56eaf691ab9393a94a1c60 # v1.60.0
        with:
          shell: release

      - name: Release to GitHub
        run: |
          set -euo pipefail
          gh release create "${TAG}" --repo "${REPOSITORY}" --title "${TAG}" --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          TAG: ${{ github.ref_name }}
